### ISSUE TITLE
GraphQL error

### ISSUE THREAD

**Issue by AiMo-Hux** [sabrinaluo/gatsby-theme-replica#1]
ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Expected type MdxFieldsEnum, found frontmatter___tags. Did you mean the enum value frontmatter___date,
frontmatter___title, or frontmatter___description?

File: node_modules\gatsby-theme-replica\gatsby-node.js:54:24

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Expected type MdxFieldsEnum, found frontmatter___category. Did you mean the enum value frontmatter___date,
frontmatter___title, or frontmatter___description?

File: node_modules\gatsby-theme-replica\gatsby-node.js:54:24

 ERROR

error loading events Expected type MdxFieldsEnum, found frontmatter___tags. Did you mean the enum value
frontmatter___date, frontmatter___title, or frontmatter___description?

  GraphQLError: Expected type MdxFieldsEnum, found frontmatter___tags. Did you mean the enum value frontmatter___date, f
  rontmatter___title, or frontmatter___description?

**Comment by sabrinaluo** [comment]
hi @AiMo-Hux you may need to check your mdx file. Following the format of https://github.com/sabrinaluo/gatsby-theme-replica/blob/development/example/content/example-post-1.md may solve your problem
