### ISSUE TITLE
markdown 子标题自动定位的问题

### ISSUE THREAD

**Issue by yangyang5214** [sabrinaluo/gatsby-theme-replica#2]
hello， 我引入 你的  **gatsby-theme-replica** 主题， url link 和 markdown 子标题没有联动。

我测试了你的  tech 仓库代码，也是没联动的，但是我看你的 blog 是有的 

麻烦作者有空修复下 😁 

![image](https://user-images.githubusercontent.com/23392325/132950006-fb41e251-d97b-4eaa-aaf1-9ecc919ee5b5.png)

![image](https://user-images.githubusercontent.com/23392325/132950024-98894fc8-e095-4a82-b745-a20c51eb27cb.png)

**Comment by sabrinaluo** [comment]
我试了一下应该是没问题的

**Comment by yangyang5214** [comment]
好吧 。貌似是一些库版本的缘故。。。

之前用 npm install 的，报错说少一些库，自己 install 了。

刚  yarn install 试了下，可以用 😊 感谢

**Comment by yangyang5214** [comment]
补充：

经测试 ， 你项目的 tech/yarn.lock 文件是灵魂。（没有这个文件的话，需要自己手动安装 @mdx-js/mdx 和 @mdx-js/react ），然后就没那个效果了 （我是前端小白。。。见谅）

非常感谢～
